title: CIPO
logo: images/CIPO_logo.png
baseurl: /
mediaServerPath: https://s3.us-west-1.wasabisys.com/cipo-media
permalink: '/:title/'
collections:
  article:
    permalink: '/article/:slug/'
palette: cipo1
palettes:
  blue:
    sass:
      bg: '#253149'
      accent1: '#4167a6'
      accent2: '#3f8eb3'
      accent3: '#4ca07e'
      accent4: '#4ca07e'
  green:
    sass:
      bg: '#20313d'
      accent1: '#2e9692'
      accent2: '#3aa4ca'
      accent3: '#b84d50'
      accent4: '#b84d50'
  purple:
    sass:
      bg: '#312450'
      accent1: '#5e42a6'
      accent2: '#5052b5'
      accent3: '#b74e91'
      accent4: '#b74e91'
  cipo1:
    sass:
      bg: '#0d0d0d' #black
      highlight: '#f74b00'
      accent1: '#254441' #dark teal
      accent1: '#006b77' #lighter blue
      accent1: '#00171E'
      accent1: '#0d0d0d'
      accent2: '#f74b00' #orange
      accent2: '#00171E'
      accent3: '#005377' #dark blue
      accent3: '#006b77' #lighter blue
      accent3: '#00171E'
      accent3: '#254441' #dark teal
      accent4: '#0d0d0d' #dark grey
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - cipo-build.sh
  - stackbit-pull.js

contentful:
  spaces:
    - cipo-website:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        environment: ENV_CONTENTFUL_ENVIRONMENT
        #cda_query:                          # Optional
        #  include: 2
        #  limit: 100
        #all_entries: true                   # Optional - Defaults to false, only grabbing the amount set on CDA Query
        #all_entries_page_size: 1000         # Optional - Defaults to 1000, maximum amount of entries per CDA Request for all_entries
        #content_types:                      # Optional
        #  cat: MyCoolMapper
        #client_options:                     # Optional
        #  api_url: 'preview.contentful.com' # Defaults to 'api.contentful.com' which is Production
        #  max_include_resolution_depth: 5   # Optional - Defaults to 20, maximum amount of levels to resolve includes
        #base_path: app_path                 # Optional - Defaults to Current directory
        #destination: destination_in_data    # Optional - Defaults to _data/contentful/spaces
        #individual_entry_files: true        # Optional - Defaults to false
        #rich_text_mappings:                 # Optional - Defaults to {}
        #  embedded-entry-block: MyEntryRenderer

page_gen:
  - index_files: false
    data: 'contentful.spaces.cipo-website.page'
    template: page
    name: slug
    dir: ..
