title: CIPO
logo: images/CIPO_logo.png
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: cipo1
palettes:
  blue:
    sass:
      bg: '#253149'
      accent1: '#4167a6'
      accent2: '#3f8eb3'
      accent3: '#4ca07e'
      accent4: '#4ca07e'
  green:
    sass:
      bg: '#20313d'
      accent1: '#2e9692'
      accent2: '#3aa4ca'
      accent3: '#b84d50'
      accent4: '#b84d50'
  purple:
    sass:
      bg: '#312450'
      accent1: '#5e42a6'
      accent2: '#5052b5'
      accent3: '#b74e91'
      accent4: '#b74e91'
  cipo1:
    sass:
      bg: '#f74b00' #orange
      bg: '#f1a208' #light orange
      bg: '#006b77' #lighter blue
      bg: '#772400' #brown
      bg: '#442528' #burgundy
      bg: '#254441' #dark teal
      bg: '#005377' #dark blue
      bg: '#000000' #black
      accent1: '#06a77d' #green
      accent1: '#772400' #brown
      accent1: '#f74b00' #orange
      accent1: '#442528' #burgundy
      accent1: '#006b77' #lighter blue
      accent1: '#005377' #dark blue
      accent1: '#254441' #dark teal
      accent2: '#254441' #dark teal
      accent2: '#006b77' #lighter blue
      accent2: '#D5C67A' #beige
      accent2: '#06a77d' #green
      accent2: '#772400' #brown
      accent2: '#442528' #burgundy
      accent2: '#005377' #dark blue
      accent2: '#f74b00' #orange
      accent3: '#06a77d' #green
      accent3: '#254441' #dark teal
      accent3: '#772400' #brown
      accent3: '#005377' #dark blue
      accent3: '#f74b00' #orange
      accent3: '#006b77' #lighter blue
      accent4: '#f74b00' #orange
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-strapi
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - cipo-build.sh
  - stackbit-pull.js

strapi:
  # Your API endpoint (optional, default to http://localhost:1337)
  # endpoint: http://localhost:1337
  endpoint: http://cms.cipo.ca:1337
  # Collections, key is used to access in the strapi.collections
  # template variable
  collections:
    # Example for a "posts" collection
    articles:
      # Collection name (optional). Used to construct the url requested. Example: type `foo` would generate the following url `http://localhost:1337/foo`.
      type: articles
      # Permalink used to generate the output files (eg. /posts/:id).
      permalink: /articles/:slug/
      layout: article.html
      # Generate output files or not (default: false)
      output: true
    videos:
      # Collection name (optional). Used to construct the url requested. Example: type `foo` would generate the following url `http://localhost:1337/foo`.
      type: videos
      # Permalink used to generate the output files (eg. /posts/:id).
      permalink: /videos/:id/
      layout: video.html
      # Generate output files or not (default: false)
      output: true
